### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by falemagn** [rollbear/visit#1]
Hi, visit_test from current trunk produces the following result.

```
$ ./visit_test 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
visit_test is a Catch v2.5.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
Scenario: single variant visit
      Given: a variant and a visitor
   And when: visited when empty with exception
       Then: visit throws bad_variant_access
-------------------------------------------------------------------------------
/home/fabio/Projects/visit/tests.cpp:80
...............................................................................

/home/fabio/Projects/visit/tests.cpp:82: FAILED:
  REQUIRE_THROWS_AS( rollbear::visit(visitor, v), std::bad_variant_access )
because no exception was thrown where one was expected:

-------------------------------------------------------------------------------
Scenario: multi variant visit
      Given: two variants and a visitor
   And when: visited when empty with exception
       Then: visit throws bad_variant_access
-------------------------------------------------------------------------------
/home/fabio/Projects/visit/tests.cpp:130
...............................................................................

/home/fabio/Projects/visit/tests.cpp:132: FAILED:
  REQUIRE_THROWS_AS( rollbear::visit(visitor, v1,v2), std::bad_variant_access )
because no exception was thrown where one was expected:

-------------------------------------------------------------------------------
Scenario: mixed types visit
      Given: two variants, a unique_ptr and a visitor
   And when: either variant is valueless by exception
       Then: visit throws bad_variant_access
-------------------------------------------------------------------------------
/home/fabio/Projects/visit/tests.cpp:214
...............................................................................

/home/fabio/Projects/visit/tests.cpp:214: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:  3 |  0 passed | 3 failed
assertions: 21 | 18 passed | 3 failed
```

For reference:
```
$ c++ --version
c++ (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by rollbear** [comment]
Thank you. I'll look into it.

**Comment by rollbear** [comment]
So, this one's curious. It depends on the version of the C++ standard library. I'm not yet sure why some versions do not cause the invariant to be `valueless_by_exception`. I think they should be, but maybe I misread the standard, but if I do, it seems like at least some maintainers of the std also do.

**Comment by rollbear** [comment]
Got a response. The libstdc++ devs are clever. The idea is not wrong, but the test code is too trivial for the clever lib devs, so I need to think a bit about how to write better tests.

https://twitter.com/BarryRevzin/status/1361826113543110657

**Comment by rollbear** [comment]
I'm not entirely convinced that the clever dev's of libstdc++ are following the requirements from the standard document, though:

http://eel.is/c++draft/variant.variant#variant.mod-7

As I understand it, `.emplace<>` must first destroy, and then try to construct.

But my interpretation is kind of meaningless, because the lib is out there and in wide use (and I actually like the implementation better than my interpretation of the standard.)

**Comment by rollbear** [comment]
This was a heck of a lot trickier to fix than I ever thought.

**Comment by falemagn** [comment]
Hey, that was an interesting discussion on Twitter. I tend to agree with what the other guy said: even though the sequence of steps is the one you mention, given that the object is **permitted** to be in valueless state, but not **mandated** to do so, an observer can't meaningfully see the difference, unless they know about the internals of the variant.

This means that a test which is implementation-agnostic can't be performed, I guess? Even though the one you just wrote should work across all existing implementations.

Thanks for your time and effort! I spent the last 4 days digging into variants and visitation thereof, implementing my own stuff and comparing it with yours, the standard and mpark's. It's been an interesting learning experience.
